/**
 * Tests for the readiness classifier — `classify(inputs): Finding[]`.
 *
 * AC6: ALL tests are pure — they pass literal in-memory `ReadinessInputs` objects.
 * No disk, no Magnific Space, no Apify, no network. No fake is needed because `classify`
 * has no I/O boundary — the conductor performs the probes and passes results in as inputs.
 *
 * Test matrix covers every severity×phase combination:
 *   block × research    — apify_token_invalid, no_valid_seed
 *   advisory × research — space_inaccessible_advisory, credits_low_advisory, null_baseline,
 *                         off_niche_seed, empty_banned_words
 *   block × production  — space_inaccessible, credits_low
 *   block × publish     — channel_url_missing
 *   (advisory × production and advisory × publish are not generated by classify — deliberate)
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { classify } from "./classify.ts";
import type { Finding, ReadinessInputs } from "./types.ts";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** A fully-healthy inputs object — no findings expected. */
const HEALTHY: ReadinessInputs = {
  apifyTokenValid: true,
  seedCount: 3,
  offNicheSeedCount: 0,
  spaceAccessible: true,
  creditsOk: true,
  channelUrl: "https://www.facebook.com/testpage",
  baseline: 0.5,
  bannedWordsEmpty: false,
};

function withOverrides(overrides: Partial<ReadinessInputs>): ReadinessInputs {
  return { ...HEALTHY, ...overrides };
}

function findingsWhere(findings: Finding[], pred: Partial<Finding>): Finding[] {
  return findings.filter((f) =>
    Object.entries(pred).every(([k, v]) => (f as unknown as Record<string, unknown>)[k] === v),
  );
}

// ---------------------------------------------------------------------------
// AC1: classify returns Finding[] with severity and phase fields
// ---------------------------------------------------------------------------

describe("classify — return shape (AC1)", () => {
  it("returns an array", () => {
    const result = classify(HEALTHY);
    assert.ok(Array.isArray(result), "classify must return an array");
  });

  it("each finding has severity, phase, code, and message fields", () => {
    const result = classify(withOverrides({ apifyTokenValid: false }));
    assert.ok(result.length > 0, "expected at least one finding");
    for (const f of result) {
      assert.ok(
        f.severity === "block" || f.severity === "advisory",
        `unexpected severity: ${f.severity}`,
      );
      assert.ok(
        f.phase === "research" || f.phase === "production" || f.phase === "publish",
        `unexpected phase: ${f.phase}`,
      );
      assert.equal(typeof f.code, "string");
      assert.ok(f.code.length > 0, "code must be non-empty");
      assert.equal(typeof f.message, "string");
      assert.ok(f.message.length > 0, "message must be non-empty");
    }
  });

  it("severity is exactly 'block' or 'advisory' — no other value", () => {
    const allInputs: ReadinessInputs[] = [
      HEALTHY,
      withOverrides({ apifyTokenValid: false }),
      withOverrides({ seedCount: 0 }),
      withOverrides({ spaceAccessible: false }),
      withOverrides({ creditsOk: false }),
      withOverrides({ channelUrl: null }),
      withOverrides({ baseline: null }),
    ];
    for (const inp of allInputs) {
      for (const f of classify(inp)) {
        assert.ok(
          f.severity === "block" || f.severity === "advisory",
          `unexpected severity: ${f.severity}`,
        );
      }
    }
  });

  it("phase is exactly 'research', 'production', or 'publish' — no other value", () => {
    const allInputs: ReadinessInputs[] = [
      HEALTHY,
      withOverrides({ apifyTokenValid: false }),
      withOverrides({ seedCount: 0 }),
      withOverrides({ spaceAccessible: false }),
      withOverrides({ creditsOk: false }),
      withOverrides({ channelUrl: null }),
      withOverrides({ baseline: null }),
    ];
    for (const inp of allInputs) {
      for (const f of classify(inp)) {
        assert.ok(
          f.phase === "research" || f.phase === "production" || f.phase === "publish",
          `unexpected phase: ${f.phase}`,
        );
      }
    }
  });
});

// ---------------------------------------------------------------------------
// AC2: Phase-scoped blocking
// ---------------------------------------------------------------------------

describe("classify — phase-scoped blocking (AC2)", () => {
  // --- block × research ---

  it("bad Apify token → block on research (code: apify_token_invalid)", () => {
    const findings = classify(withOverrides({ apifyTokenValid: false }));
    const match = findingsWhere(findings, { severity: "block", phase: "research", code: "apify_token_invalid" });
    assert.equal(match.length, 1, "expected exactly one apify_token_invalid finding");
  });

  it("bad Apify token → no block on production", () => {
    const findings = classify(withOverrides({ apifyTokenValid: false }));
    const productionBlocks = findingsWhere(findings, { severity: "block", phase: "production" });
    assert.equal(productionBlocks.length, 0, "bad Apify token must not block production");
  });

  it("bad Apify token → no block on publish", () => {
    const findings = classify(withOverrides({ apifyTokenValid: false }));
    const publishBlocks = findingsWhere(findings, { severity: "block", phase: "publish" });
    assert.equal(publishBlocks.length, 0, "bad Apify token must not block publish");
  });

  it("no valid seed (seedCount: 0) → block on research (code: no_valid_seed)", () => {
    const findings = classify(withOverrides({ seedCount: 0 }));
    const match = findingsWhere(findings, { severity: "block", phase: "research", code: "no_valid_seed" });
    assert.equal(match.length, 1, "expected exactly one no_valid_seed finding");
  });

  it("no valid seed → no block on production or publish", () => {
    const findings = classify(withOverrides({ seedCount: 0 }));
    const nonResearchBlocks = findings.filter(
      (f) => f.severity === "block" && f.phase !== "research",
    );
    assert.equal(nonResearchBlocks.length, 0, "no_valid_seed must only block research");
  });

  // --- advisory × research + block × production (Space inaccessible) ---

  it("inaccessible Space → advisory on research (code: space_inaccessible_advisory)", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    const match = findingsWhere(findings, {
      severity: "advisory",
      phase: "research",
      code: "space_inaccessible_advisory",
    });
    assert.equal(match.length, 1, "expected one space_inaccessible_advisory finding");
  });

  it("inaccessible Space → block on production (code: space_inaccessible)", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    const match = findingsWhere(findings, {
      severity: "block",
      phase: "production",
      code: "space_inaccessible",
    });
    assert.equal(match.length, 1, "expected one space_inaccessible block on production");
  });

  it("inaccessible Space → no block on research", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    const researchBlocks = findingsWhere(findings, { severity: "block", phase: "research" });
    assert.equal(researchBlocks.length, 0, "Space inaccessible must not block research");
  });

  it("inaccessible Space → no block on publish", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    const publishBlocks = findingsWhere(findings, { severity: "block", phase: "publish" });
    assert.equal(publishBlocks.length, 0, "Space inaccessible must not block publish");
  });

  // --- advisory × research + block × production (credits low) ---

  it("insufficient credits → advisory on research (code: credits_low_advisory)", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    const match = findingsWhere(findings, {
      severity: "advisory",
      phase: "research",
      code: "credits_low_advisory",
    });
    assert.equal(match.length, 1, "expected one credits_low_advisory finding");
  });

  it("insufficient credits → block on production (code: credits_low)", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    const match = findingsWhere(findings, {
      severity: "block",
      phase: "production",
      code: "credits_low",
    });
    assert.equal(match.length, 1, "expected one credits_low block on production");
  });

  it("insufficient credits → no block on research", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    const researchBlocks = findingsWhere(findings, { severity: "block", phase: "research" });
    assert.equal(researchBlocks.length, 0, "insufficient credits must not block research");
  });

  it("insufficient credits → no block on publish", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    const publishBlocks = findingsWhere(findings, { severity: "block", phase: "publish" });
    assert.equal(publishBlocks.length, 0, "insufficient credits must not block publish");
  });

  // --- block × publish ---

  it("missing Channel URL → block on publish (code: channel_url_missing)", () => {
    const findings = classify(withOverrides({ channelUrl: null }));
    const match = findingsWhere(findings, {
      severity: "block",
      phase: "publish",
      code: "channel_url_missing",
    });
    assert.equal(match.length, 1, "expected one channel_url_missing block on publish");
  });

  it("missing Channel URL → no block on research", () => {
    const findings = classify(withOverrides({ channelUrl: null }));
    const researchBlocks = findingsWhere(findings, { severity: "block", phase: "research" });
    assert.equal(researchBlocks.length, 0, "missing channel URL must not block research");
  });

  it("missing Channel URL → no block on production", () => {
    const findings = classify(withOverrides({ channelUrl: null }));
    const productionBlocks = findingsWhere(findings, { severity: "block", phase: "production" });
    assert.equal(productionBlocks.length, 0, "missing channel URL must not block production");
  });
});

// ---------------------------------------------------------------------------
// AC3: Pure advisories never block any phase
// ---------------------------------------------------------------------------

describe("classify — pure advisories (AC3)", () => {
  it("null baseline → advisory on research (code: null_baseline)", () => {
    const findings = classify(withOverrides({ baseline: null }));
    const match = findingsWhere(findings, {
      severity: "advisory",
      phase: "research",
      code: "null_baseline",
    });
    assert.equal(match.length, 1, "expected one null_baseline advisory");
  });

  it("null baseline → no block on any phase", () => {
    const findings = classify(withOverrides({ baseline: null }));
    const blocks = findings.filter((f) => f.severity === "block");
    assert.equal(blocks.length, 0, "null baseline must not produce any block finding");
  });

  it("null baseline only — no extraneous findings from healthy rest of inputs", () => {
    const findings = classify(withOverrides({ baseline: null }));
    assert.equal(findings.length, 1, "only one finding for a null baseline with otherwise healthy inputs");
  });

  // --- off-niche seed (AC3) ---

  it("offNicheSeedCount > 0 → advisory on research (code: off_niche_seed)", () => {
    const findings = classify(withOverrides({ offNicheSeedCount: 2 }));
    const match = findingsWhere(findings, {
      severity: "advisory",
      phase: "research",
      code: "off_niche_seed",
    });
    assert.equal(match.length, 1, "expected one off_niche_seed advisory");
  });

  it("offNicheSeedCount > 0 → no block on any phase", () => {
    const findings = classify(withOverrides({ offNicheSeedCount: 2 }));
    const blocks = findings.filter((f) => f.severity === "block");
    assert.equal(blocks.length, 0, "off-niche seed must not produce any block finding");
  });

  it("offNicheSeedCount: 0 → no off_niche_seed finding", () => {
    const findings = classify(withOverrides({ offNicheSeedCount: 0 }));
    const match = findingsWhere(findings, { code: "off_niche_seed" });
    assert.equal(match.length, 0, "offNicheSeedCount: 0 must not produce an off_niche_seed finding");
  });

  // --- empty banned-words (AC3) ---

  it("bannedWordsEmpty: true → advisory on research (code: empty_banned_words)", () => {
    const findings = classify(withOverrides({ bannedWordsEmpty: true }));
    const match = findingsWhere(findings, {
      severity: "advisory",
      phase: "research",
      code: "empty_banned_words",
    });
    assert.equal(match.length, 1, "expected one empty_banned_words advisory");
  });

  it("bannedWordsEmpty: true → no block on any phase", () => {
    const findings = classify(withOverrides({ bannedWordsEmpty: true }));
    const blocks = findings.filter((f) => f.severity === "block");
    assert.equal(blocks.length, 0, "empty banned-words must not produce any block finding");
  });

  it("bannedWordsEmpty: false → no empty_banned_words finding", () => {
    const findings = classify(withOverrides({ bannedWordsEmpty: false }));
    const match = findingsWhere(findings, { code: "empty_banned_words" });
    assert.equal(match.length, 0, "bannedWordsEmpty: false must not produce an empty_banned_words finding");
  });
});

// ---------------------------------------------------------------------------
// AC3: Healthy inputs produce no findings (full-healthy matrix)
// ---------------------------------------------------------------------------

describe("classify — healthy inputs → no findings", () => {
  it("all fields valid → empty finding list", () => {
    const findings = classify(HEALTHY);
    assert.deepEqual(findings, [], "healthy inputs must produce no findings");
  });
});

// ---------------------------------------------------------------------------
// AC2 + AC3: Multiple problems produce multiple findings
// ---------------------------------------------------------------------------

describe("classify — multiple problems produce multiple findings", () => {
  it("all-bad inputs → at least 6 findings (one per condition plus advisory+block pairs)", () => {
    const allBad: ReadinessInputs = {
      apifyTokenValid: false,
      seedCount: 0,
      offNicheSeedCount: 0,
      spaceAccessible: false,
      creditsOk: false,
      channelUrl: null,
      baseline: null,
      bannedWordsEmpty: false,
    };
    const findings = classify(allBad);
    // apify_token_invalid(research block) + no_valid_seed(research block) +
    // space_inaccessible_advisory(research) + space_inaccessible(production block) +
    // credits_low_advisory(research) + credits_low(production block) +
    // channel_url_missing(publish block) + null_baseline(research advisory) = 8
    assert.ok(findings.length >= 6, `expected at least 6 findings, got ${findings.length}`);
  });

  it("all-bad inputs → covers research block, production block, publish block, and advisories", () => {
    const allBad: ReadinessInputs = {
      apifyTokenValid: false,
      seedCount: 0,
      offNicheSeedCount: 0,
      spaceAccessible: false,
      creditsOk: false,
      channelUrl: null,
      baseline: null,
      bannedWordsEmpty: false,
    };
    const findings = classify(allBad);
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "research"),
      "must have a block on research",
    );
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "production"),
      "must have a block on production",
    );
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "publish"),
      "must have a block on publish",
    );
    assert.ok(
      findings.some((f) => f.severity === "advisory"),
      "must have at least one advisory",
    );
  });
});

// ---------------------------------------------------------------------------
// AC5: Deterministic ordering
// ---------------------------------------------------------------------------

describe("classify — deterministic ordering (AC5)", () => {
  it("same inputs always produce the same finding list", () => {
    const inputs: ReadinessInputs = {
      apifyTokenValid: false,
      seedCount: 0,
      offNicheSeedCount: 0,
      spaceAccessible: false,
      creditsOk: false,
      channelUrl: null,
      baseline: null,
      bannedWordsEmpty: false,
    };
    const first = classify(inputs);
    const second = classify(inputs);
    assert.deepEqual(first, second, "classify must be deterministic");
  });

  it("findings are ordered: research < production < publish (by phase)", () => {
    const inputs: ReadinessInputs = {
      apifyTokenValid: false,
      seedCount: 0,
      offNicheSeedCount: 0,
      spaceAccessible: false,
      creditsOk: false,
      channelUrl: null,
      baseline: null,
      bannedWordsEmpty: false,
    };
    const findings = classify(inputs);
    const phaseOrder = new Map([["research", 0], ["production", 1], ["publish", 2]]);
    for (let i = 1; i < findings.length; i++) {
      const prev = phaseOrder.get(findings[i - 1]!.phase) ?? 0;
      const curr = phaseOrder.get(findings[i]!.phase) ?? 0;
      assert.ok(prev <= curr, `finding[${i - 1}].phase=${findings[i - 1]!.phase} must come before finding[${i}].phase=${findings[i]!.phase}`);
    }
  });

  it("within the same phase, block findings come before advisory findings", () => {
    const inputs2: ReadinessInputs = {
      apifyTokenValid: false, // block research
      seedCount: 0,           // block research
      offNicheSeedCount: 0,
      spaceAccessible: false, // advisory research + block production
      creditsOk: false,       // advisory research + block production
      channelUrl: null,       // block publish
      baseline: null,         // advisory research
      bannedWordsEmpty: false,
    };
    const findings = classify(inputs2);
    // Within each phase group, verify blocks precede advisories
    const phases: Array<"research" | "production" | "publish"> = ["research", "production", "publish"];
    for (const phase of phases) {
      const group = findings.filter((f) => f.phase === phase);
      let seenAdvisory = false;
      for (const f of group) {
        if (f.severity === "advisory") seenAdvisory = true;
        if (f.severity === "block") {
          assert.ok(!seenAdvisory, `block finding with code=${f.code} appeared after an advisory in phase=${phase}`);
        }
      }
    }
  });

  it("within same phase+severity, findings are ordered alphabetically by code", () => {
    // Trigger two research blocks: apify_token_invalid and no_valid_seed
    const inputs = withOverrides({ apifyTokenValid: false, seedCount: 0 });
    const findings = classify(inputs);
    const researchBlocks = findings.filter((f) => f.phase === "research" && f.severity === "block");
    for (let i = 1; i < researchBlocks.length; i++) {
      const prev = researchBlocks[i - 1]!.code;
      const curr = researchBlocks[i]!.code;
      assert.ok(
        prev <= curr,
        `research blocks must be alphabetically ordered by code: ${prev} should come before ${curr}`,
      );
    }
  });
});

// ---------------------------------------------------------------------------
// AC6 (explicit): No live Magnific/Apify calls — results fed in as inputs
// ---------------------------------------------------------------------------

describe("classify — no live calls (AC6)", () => {
  it("classify accepts plain ReadinessInputs and needs no mocks (pure function)", () => {
    // If classify were to make any live call, this would timeout or throw.
    // The fact it returns synchronously with no mock setup proves purity.
    const result = classify({
      apifyTokenValid: true,
      seedCount: 2,
      offNicheSeedCount: 0,
      spaceAccessible: true,
      creditsOk: true,
      channelUrl: "https://fb.com/page",
      baseline: 0.8,
      bannedWordsEmpty: false,
    });
    assert.ok(Array.isArray(result), "classify is a synchronous pure function returning an array");
  });

  it("classify returns synchronously (not a Promise)", () => {
    const result = classify(HEALTHY);
    assert.ok(!(result instanceof Promise), "classify must return synchronously");
  });
});

// ---------------------------------------------------------------------------
// Severity×Phase coverage matrix (AC6 — explicit matrix)
// ---------------------------------------------------------------------------

describe("classify — severity×phase coverage matrix (AC6)", () => {
  it("block × research covered: apify_token_invalid", () => {
    const findings = classify(withOverrides({ apifyTokenValid: false }));
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "research"),
      "block × research must be reachable",
    );
  });

  it("block × research covered: no_valid_seed", () => {
    const findings = classify(withOverrides({ seedCount: 0 }));
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "research"),
      "block × research must be reachable via seedCount: 0",
    );
  });

  it("advisory × research covered: space_inaccessible_advisory", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    assert.ok(
      findings.some((f) => f.severity === "advisory" && f.phase === "research"),
      "advisory × research must be reachable via spaceAccessible: false",
    );
  });

  it("advisory × research covered: credits_low_advisory", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    assert.ok(
      findings.some((f) => f.severity === "advisory" && f.phase === "research"),
      "advisory × research must be reachable via creditsOk: false",
    );
  });

  it("advisory × research covered: null_baseline", () => {
    const findings = classify(withOverrides({ baseline: null }));
    assert.ok(
      findings.some((f) => f.severity === "advisory" && f.phase === "research"),
      "advisory × research must be reachable via baseline: null",
    );
  });

  it("advisory × research covered: off_niche_seed", () => {
    const findings = classify(withOverrides({ offNicheSeedCount: 1 }));
    assert.ok(
      findings.some((f) => f.severity === "advisory" && f.phase === "research" && f.code === "off_niche_seed"),
      "advisory × research must be reachable via offNicheSeedCount: 1",
    );
  });

  it("advisory × research covered: empty_banned_words", () => {
    const findings = classify(withOverrides({ bannedWordsEmpty: true }));
    assert.ok(
      findings.some((f) => f.severity === "advisory" && f.phase === "research" && f.code === "empty_banned_words"),
      "advisory × research must be reachable via bannedWordsEmpty: true",
    );
  });

  it("block × production covered: space_inaccessible", () => {
    const findings = classify(withOverrides({ spaceAccessible: false }));
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "production"),
      "block × production must be reachable via spaceAccessible: false",
    );
  });

  it("block × production covered: credits_low", () => {
    const findings = classify(withOverrides({ creditsOk: false }));
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "production"),
      "block × production must be reachable via creditsOk: false",
    );
  });

  it("block × publish covered: channel_url_missing", () => {
    const findings = classify(withOverrides({ channelUrl: null }));
    assert.ok(
      findings.some((f) => f.severity === "block" && f.phase === "publish"),
      "block × publish must be reachable via channelUrl: null",
    );
  });
});
