/**
 * The SQLite schema — one migration runner's worth of DDL for the local, in-process database ADR-0029
 * lands (issue #201, epic #195).
 *
 * A pure, deterministic deep module: it builds SQL TEXT (no disk, no network, no clock, no open
 * `DatabaseSync` handle) so it can be unit-tested on its own and reused unchanged by `migrate.ts`'s
 * orchestration shell. Nothing here talks to the filesystem or opens a connection — `connection.ts`
 * and `migrate.ts` do that.
 *
 * ## Covers every entity CONTEXT.md names (AC5, epic #195's schema section)
 *
 * `brand`, `channel`, `format`, `baseline_prompt`, `brand_asset` (tenancy/config); `run`, `trend`,
 * `idea`, `idea_recipe`, `asset`, `asset_media`, `copy_variant`, `job`, `gate_request` (the work);
 * `post`, `metric_snapshot`, `performance_score`, `channel_baseline` (the feedback loop). Every table
 * carries `id` (a stable surrogate id, TEXT — generated by the caller via `crypto.randomUUID()`,
 * mirroring `src/camera-hub/library.ts`'s existing convention; SQLite has no native UUID type),
 * `created_at`, `updated_at` (ISO-8601 strings) and `schema_version` (an INTEGER, defaulting to this
 * migration's own version — the version stamp no file in this repo has ever carried, and could never be
 * backfilled onto: "No file carries a version stamp, `updated_at`, or an etag" — epic #195's problem
 * statement). Read literally: an entity table's `schema_version` DEFAULT is baked into the `CREATE
 * TABLE` statement of whichever migration actually defined that table's shape — NOT necessarily
 * `CURRENT_SCHEMA_VERSION` (the highest version among ALL `MIGRATIONS`, structural or not). SQLite has
 * no `ALTER COLUMN ... SET DEFAULT`, so a later migration that never touches a given entity table's DDL
 * (like migration 2, issue #219, which only seeds `hook_type_vocabulary`/`theme_vocabulary`) leaves that
 * table's own DEFAULT exactly as its defining migration set it. The two numbers happened to be equal
 * while only one migration existed; migration 2 is the first case where they diverge.
 *
 * ## Closed vocabularies are REFERENCE TABLES, not just CHECK constraints
 *
 * `hook_type_vocabulary` and `theme_vocabulary` are seeded, at migration time, from
 * `src/vocabulary/hook-type.ts`'s `HOOK_TYPES` and `src/vocabulary/theme.ts`'s `THEMES` — the SAME
 * arrays `CONTEXT.md`'s glossary entries are asserted against (`context-md.docs-test.ts`). `idea.hook_type`
 * / `idea.theme` are real FOREIGN KEYs into those tables, enforced by `PRAGMA foreign_keys = ON`
 * (`connection.ts`) — not merely a static CHECK list that could silently diverge from the TypeScript
 * source. `recipe_vocabulary` does the identical thing for `src/recipe/registry.ts`'s
 * `listWiredRecipeSlugs()` (AC7: "trust the registry, not CONTEXT.md's count of two" — the registry IS
 * the seed source, so there is nothing left to trust separately). Widening any of these three sets is a
 * NEW migration (an `INSERT` for the new row(s)), never an edit to this migration's already-shipped SQL
 * — proven out by migration 2 (issue #219), which adds ONLY the `unclassified` row to
 * `hook_type_vocabulary`/`theme_vocabulary`, on top of migration 1's already-shipped ten/nine.
 *
 * `channel.platform` / `trend.platform` use a plain CHECK against `KNOWN_PLATFORMS`
 * (`src/copy/platform-shape.ts`) — that list is already a live, tested constant elsewhere in this
 * codebase and is smaller-stakes than the two vocabularies this issue exists to close, so a reference
 * table would be ceremony without benefit. `format.cadence` / `run.cadence` (`'weekly'|'daily'`,
 * ADR-0022) and `format.source_mode` (`'peer'|'curated'`, ADR-0013) are likewise plain CHECKs, mirroring
 * `src/format/store.ts`'s existing `FormatCadence`/`FormatSourceMode` TS union types (kept in sync by
 * hand — both are two-value sets fixed by an already-decided ADR, not open-ended).
 *
 * ## What this migration deliberately does NOT build
 *
 * `account`, `user`, `connection` — the epic's own "leave room, don't build" instruction (AC12). No
 * column here reshapes if/when they arrive: a future migration adds those three tables plus an
 * OPTIONAL `account_id` column on `brand` (SQLite's `ALTER TABLE ... ADD COLUMN` supports a nullable
 * addition without a table rebuild). See `docs/adr/0029` for the full reasoning.
 */

import { HOOK_TYPES, UNCLASSIFIED_HOOK_TYPE } from "../vocabulary/hook-type.ts";
import { THEMES, UNCLASSIFIED_THEME } from "../vocabulary/theme.ts";
import { listWiredRecipeSlugs, getRecipe } from "../recipe/registry.ts";
import { KNOWN_PLATFORMS } from "../copy/platform-shape.ts";

/** One migration: an ordered, numbered slab of DDL/DML applied atomically, once, and recorded. */
export interface Migration {
  readonly version: number;
  readonly description: string;
  readonly sql: string;
}

/** Every entity table this schema creates (excludes the bookkeeping `schema_migrations` table and the
 *  three seeded vocabulary/reference tables, which are enumerated separately below). Exported so tests
 *  can generically assert "every entity table carries id/created_at/updated_at/schema_version" without
 *  hand-maintaining a second copy of this list. */
export const ENTITY_TABLES = [
  "brand",
  "channel",
  "format",
  "baseline_prompt",
  "brand_asset",
  "run",
  "trend",
  "idea",
  "idea_recipe",
  "asset",
  "asset_media",
  "copy_variant",
  "job",
  "gate_request",
  "post",
  "metric_snapshot",
  "performance_score",
  "channel_baseline",
] as const;

/**
 * `schedule_outbox` (issue #209, migration 3) is deliberately NOT one of `ENTITY_TABLES` above: it is
 * engineering infrastructure (the outbox-pattern reserve/confirm ledger for Zoho scheduling calls), not
 * one of the domain entities `CONTEXT.md` names — `ENTITY_TABLES`' own Requirement (`sqlite-foundation`
 * spec) is specifically "every entity CONTEXT.md names", and mixing in a non-domain table would make
 * that claim inaccurate. It still carries the SAME `id`/`created_at`/`updated_at`/`schema_version`
 * columns as every `ENTITY_TABLES` member (proven directly, not via that generic loop —
 * `src/db/schema.test.ts`).
 */
export const OUTBOX_TABLES = ["schedule_outbox"] as const;

/** The three seeded, closed-vocabulary reference tables (distinct from `ENTITY_TABLES`: these carry no
 *  `updated_at`/`schema_version` of their own — they are lookup data, not per-Brand records). */
export const VOCABULARY_TABLES = ["hook_type_vocabulary", "theme_vocabulary", "recipe_vocabulary"] as const;

/** Escapes a value for embedding as a single-quoted SQL string literal. None of this schema's own
 *  vocabulary/platform/slug values contain a quote today, but every embedding goes through this so a
 *  future value safely can. */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Renders a `(v1, v2, ...)` SQL list for a `CHECK (col IN (...))` / `REFERENCES` seed clause. */
function sqlList(values: readonly string[]): string {
  return `(${values.map(sqlString).join(", ")})`;
}

const PLATFORM_CHECK = sqlList([...KNOWN_PLATFORMS]);

/**
 * Migration 1's own seed rows for `hook_type_vocabulary`/`theme_vocabulary` — the original ten Hook
 * Types and nine Themes issue #201 shipped, EXCLUDING `unclassified` (issue #219's addition). Filtering
 * the live `HOOK_TYPES`/`THEMES` arrays down to this snapshot (rather than mapping them in full) is what
 * keeps migration 1's generated SQL identical to what it already shipped, even though `unclassified` is
 * now a permanent member of those same arrays — still derived from the one TypeScript source, never a
 * second hand-copied list, just partitioned by which migration introduced each row.
 */
const MIGRATION_1_HOOK_TYPES = HOOK_TYPES.filter((t) => t.value !== UNCLASSIFIED_HOOK_TYPE);
const MIGRATION_1_THEMES = THEMES.filter((t) => t.value !== UNCLASSIFIED_THEME);

/** Migration 1: the whole initial schema — every entity table, the three seeded vocabulary tables, and
 *  their seed data, built fresh from `src/vocabulary/*` and `src/recipe/registry.ts` so nothing here is
 *  a second, hand-copied list. */
const MIGRATION_1: Migration = {
  version: 1,
  description: "Initial schema: every CONTEXT.md entity, plus the seeded closed-vocabulary tables.",
  sql: `
-- Tenancy / configuration ----------------------------------------------------------------------

CREATE TABLE brand (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  banned_words_json TEXT NOT NULL DEFAULT '[]',
  required_cta TEXT,
  required_hashtags_json TEXT NOT NULL DEFAULT '[]',
  watermark_handle TEXT,
  media_root TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE channel (
  id TEXT PRIMARY KEY,
  brand_id TEXT NOT NULL REFERENCES brand(id),
  platform TEXT NOT NULL CHECK (platform IN ${PLATFORM_CHECK}),
  url TEXT NOT NULL DEFAULT '',
  handle TEXT,
  is_primary INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  is_tracked INTEGER NOT NULL DEFAULT 0 CHECK (is_tracked IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);
-- Exactly one primary Channel per Brand (ADR-0019) — a partial unique index, not a CHECK, because a
-- CHECK cannot see sibling rows.
CREATE UNIQUE INDEX idx_channel_one_primary_per_brand ON channel(brand_id) WHERE is_primary = 1;

CREATE TABLE format (
  id TEXT PRIMARY KEY,
  brand_id TEXT NOT NULL REFERENCES brand(id),
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  voice TEXT NOT NULL,
  cadence TEXT NOT NULL CHECK (cadence IN ('weekly', 'daily')),
  ideas_per_run INTEGER NOT NULL,
  source_mode TEXT NOT NULL CHECK (source_mode IN ('peer', 'curated')),
  sources_json TEXT NOT NULL DEFAULT '{}',
  default_recipes_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (brand_id, slug)
);

CREATE TABLE recipe_vocabulary (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE baseline_prompt (
  id TEXT PRIMARY KEY,
  format_id TEXT NOT NULL REFERENCES format(id),
  recipe_slug TEXT NOT NULL REFERENCES recipe_vocabulary(slug),
  document_ref TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (format_id, recipe_slug)
);

CREATE TABLE brand_asset (
  id TEXT PRIMARY KEY,
  brand_id TEXT NOT NULL REFERENCES brand(id),
  key TEXT NOT NULL,
  storage_key TEXT NOT NULL,
  mime TEXT NOT NULL,
  bytes INTEGER NOT NULL,
  checksum TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (brand_id, key)
);

-- The work --------------------------------------------------------------------------------------

CREATE TABLE run (
  id TEXT PRIMARY KEY,
  brand_id TEXT NOT NULL REFERENCES brand(id),
  format_id TEXT NOT NULL REFERENCES format(id),
  run_key TEXT NOT NULL,
  cadence TEXT NOT NULL CHECK (cadence IN ('weekly', 'daily')),
  started_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (format_id, run_key)
);

CREATE TABLE trend (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES run(id),
  label TEXT NOT NULL,
  momentum REAL,
  source_urls_json TEXT NOT NULL DEFAULT '[]',
  platform TEXT CHECK (platform IS NULL OR platform IN ${PLATFORM_CHECK}),
  is_paywalled INTEGER NOT NULL DEFAULT 0 CHECK (is_paywalled IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE hook_type_vocabulary (
  value TEXT PRIMARY KEY,
  meaning TEXT NOT NULL
);

CREATE TABLE theme_vocabulary (
  value TEXT PRIMARY KEY,
  meaning TEXT NOT NULL
);

CREATE TABLE idea (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES run(id),
  brand_id TEXT NOT NULL REFERENCES brand(id),
  format_id TEXT NOT NULL REFERENCES format(id),
  -- Nullable: a future importer (issue #204) may meet a legacy Idea with no recorded Trend (e.g. an
  -- early or hand-migrated shape) — deliberately NOT forced NOT NULL here so this ticket's schema
  -- cannot block that decision. See docs/adr/0029's Consequences.
  trend_id TEXT REFERENCES trend(id),
  title TEXT NOT NULL,
  brief TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('suggested', 'accepted', 'rejected')),
  rejection_reason TEXT,
  fit_score REAL,
  relevance REAL,
  momentum REAL,
  brand_fit REAL,
  -- Required at Idea creation, not a nullable convenience (epic #195 Implementation Decisions) — an
  -- open text field would reproduce today's free-prose-in-a-Brief-heading problem in a new location.
  hook_type TEXT NOT NULL REFERENCES hook_type_vocabulary(value),
  theme TEXT NOT NULL REFERENCES theme_vocabulary(value),
  source_urls_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE idea_recipe (
  id TEXT PRIMARY KEY,
  idea_id TEXT NOT NULL REFERENCES idea(id),
  recipe_slug TEXT NOT NULL REFERENCES recipe_vocabulary(slug),
  chosen INTEGER NOT NULL DEFAULT 0 CHECK (chosen IN (0, 1)),
  decline_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (idea_id, recipe_slug)
);

CREATE TABLE asset (
  id TEXT PRIMARY KEY,
  idea_id TEXT NOT NULL REFERENCES idea(id),
  recipe_slug TEXT NOT NULL REFERENCES recipe_vocabulary(slug),
  -- The same six-stage ladder ADR-0011 defined for the file ledger (src/asset/asset.ts's
  -- AssetStatus) — carried forward unchanged, not reversed by ADR-0028 (docs/adr/0028's own
  -- Consequences section is explicit about this).
  status TEXT NOT NULL CHECK (status IN ('queued', 'in_production', 'produced', 'posted', 'tracking', 'scored')),
  pending_gate TEXT,
  spec_json TEXT,
  produced_at TEXT,
  scheduled_at TEXT,
  camera_hub_uploaded_at TEXT,
  zoho_schedule_ref TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (idea_id, recipe_slug)
);

CREATE TABLE asset_media (
  id TEXT PRIMARY KEY,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  ordinal INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('image', 'video', 'audio')),
  storage_key TEXT NOT NULL,
  mime TEXT NOT NULL,
  bytes INTEGER NOT NULL,
  checksum TEXT NOT NULL,
  magnific_creation_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (asset_id, ordinal)
);

CREATE TABLE copy_variant (
  id TEXT PRIMARY KEY,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  channel_id TEXT NOT NULL REFERENCES channel(id),
  caption TEXT NOT NULL,
  hashtags_json TEXT NOT NULL DEFAULT '[]',
  mentions_json TEXT NOT NULL DEFAULT '[]',
  title TEXT,
  cta TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (asset_id, channel_id)
);

CREATE TABLE job (
  id TEXT PRIMARY KEY,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  brand_id TEXT NOT NULL REFERENCES brand(id),
  gate TEXT,
  status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'awaiting_pick', 'done', 'failed')),
  -- Real claiming (an atomic UPDATE ... RETURNING against locked_by/locked_until) is issue #203's job,
  -- not this ticket's — these columns exist so that slice has room, per this ticket's own brief.
  attempt INTEGER NOT NULL DEFAULT 0,
  enqueued_at TEXT NOT NULL,
  started_at TEXT,
  idempotency_key TEXT,
  locked_by TEXT,
  locked_until TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE gate_request (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL REFERENCES job(id),
  gate_name TEXT NOT NULL,
  candidates_json TEXT NOT NULL DEFAULT '[]',
  decided_by TEXT,
  decided_at TEXT,
  choice TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

-- The feedback loop -------------------------------------------------------------------------------

CREATE TABLE post (
  id TEXT PRIMARY KEY,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  channel_id TEXT NOT NULL REFERENCES channel(id),
  post_url TEXT NOT NULL,
  posted_at TEXT NOT NULL,
  -- No closed vocabulary enforced yet — issue #203 defines the concrete tracking-state machine.
  tracking_state TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (asset_id, channel_id)
);

CREATE TABLE metric_snapshot (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES post(id),
  captured_at TEXT NOT NULL,
  reactions INTEGER,
  comments INTEGER,
  shares INTEGER,
  views INTEGER,
  source TEXT NOT NULL,
  raw_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE channel_baseline (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channel(id),
  median_reactions REAL,
  median_comments REAL,
  median_shares REAL,
  median_views REAL,
  window TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE performance_score (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES post(id),
  baseline_id TEXT REFERENCES channel_baseline(id),
  score REAL NOT NULL,
  computed_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1
);

-- Seed data: the three closed vocabularies, sourced from TypeScript, never hand-duplicated -------

${MIGRATION_1_HOOK_TYPES.map((t) => `INSERT INTO hook_type_vocabulary (value, meaning) VALUES (${sqlString(t.value)}, ${sqlString(t.meaning)});`).join("\n")}

${MIGRATION_1_THEMES.map((t) => `INSERT INTO theme_vocabulary (value, meaning) VALUES (${sqlString(t.value)}, ${sqlString(t.meaning)});`).join("\n")}

${listWiredRecipeSlugs()
  .map((slug) => {
    const recipe = getRecipe(slug);
    const name = recipe === null ? slug : recipe.name;
    return `INSERT INTO recipe_vocabulary (slug, name) VALUES (${sqlString(slug)}, ${sqlString(name)});`;
  })
  .join("\n")}
`,
};

/**
 * Migration 2's own seed rows — just the `unclassified` entries, the complement of
 * `MIGRATION_1_HOOK_TYPES`/`MIGRATION_1_THEMES` above (still derived from the one `HOOK_TYPES`/`THEMES`
 * source, never a hand-typed literal).
 */
const MIGRATION_2_HOOK_TYPES = HOOK_TYPES.filter((t) => t.value === UNCLASSIFIED_HOOK_TYPE);
const MIGRATION_2_THEMES = THEMES.filter((t) => t.value === UNCLASSIFIED_THEME);

/**
 * Migration 2 (issue #219, Operator decision 2026-08-17): adds the explicit `unclassified` member to
 * `hook_type_vocabulary` and `theme_vocabulary` — an honest, `NOT NULL`-compatible default for a Brief
 * with no classifiable Hook concept or subject, rather than making `idea.hook_type`/`idea.theme`
 * nullable (which would have conflated "not yet classified" with "has nothing to classify"). Adds ONLY
 * these two rows; every other table and constraint from migration 1 is untouched.
 */
const MIGRATION_2: Migration = {
  version: 2,
  description: "Adds the explicit 'unclassified' member to hook_type_vocabulary and theme_vocabulary.",
  sql: `
${MIGRATION_2_HOOK_TYPES.map((t) => `INSERT INTO hook_type_vocabulary (value, meaning) VALUES (${sqlString(t.value)}, ${sqlString(t.meaning)});`).join("\n")}

${MIGRATION_2_THEMES.map((t) => `INSERT INTO theme_vocabulary (value, meaning) VALUES (${sqlString(t.value)}, ${sqlString(t.meaning)});`).join("\n")}
`,
};

/**
 * Migration 3 (issue #209): adds `schedule_outbox` — the reserve/confirm ledger the outbox scheduling
 * pattern needs. The current Zoho scheduling order is "call, then write" — a crash between the two means
 * a retry double-posts publicly. This table reverses that: reserve the idempotency key (one row per
 * `(Asset, Channel target)` scheduling attempt) BEFORE calling Zoho, confirm it AFTER — so a crash
 * between the two leaves a `'reserved'`-but-not-`'confirmed'` row, never an ambiguous gap outside the
 * database. `idempotency_key` is UNIQUE: a second reservation attempt for the SAME key (a retry after a
 * crash, or a genuine resubmission) finds the EXISTING row rather than creating a second one
 * (`src/schedule-outbox/store.ts`'s `reserveScheduleOutboxEntry`). `request_json` carries the full
 * `ZohoPostRequest` (`src/schedule-batch/mcp-schedule-port.ts`) this reservation is FOR, so a resumed
 * attempt can reconcile against Zoho (`ZohoSchedulePort.listSchedules`) without the caller re-supplying
 * anything. Only two states exist — `'reserved'` and `'confirmed'` — deliberately no `'failed'`: a
 * `createSchedule` call that throws leaves the row `'reserved'`, which is exactly "not yet known to have
 * succeeded", resolved by reconciliation on the next attempt rather than a separate terminal state.
 */
const MIGRATION_3: Migration = {
  version: 3,
  description: "Adds schedule_outbox — the reserve/confirm ledger for Zoho scheduling calls.",
  sql: `
CREATE TABLE schedule_outbox (
  id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE,
  asset_id TEXT NOT NULL REFERENCES asset(id),
  platform TEXT NOT NULL CHECK (platform IN ${PLATFORM_CHECK}),
  request_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'reserved' CHECK (status IN ('reserved', 'confirmed')),
  reference_json TEXT,
  reserved_at TEXT NOT NULL,
  confirmed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 3
);
`,
};

/**
 * Migration 4 (issue #206): adds `idea.hook_type_source` / `idea.theme_source` — the queryable
 * provenance of a classification, distinct from the classification VALUE itself (`hook_type`/`theme`,
 * already `NOT NULL` since migration 1). Nullable (never `NOT NULL`): most existing `idea` rows were
 * classified before this ticket existed (or carry the importer's own `unclassified` default, issue
 * #219/#204, which records no provenance because nothing was actually read) — `NULL` here honestly means
 * "no provenance recorded," never a fabricated third value standing in for that. Each column accepts
 * exactly two values, `'heading'` (the classifier read a literal technique/subject named in the Brief's
 * own `## Hook concept`/`## Hook Concept` heading) or `'inferred'` (the classifier read the Brief as a
 * whole because the heading named no literal technique) — a plain `CHECK`, not a third seeded reference
 * table: a two-value, schema-fixed set is exactly the class of thing `schema.ts`'s own doc comment above
 * already reserves for a `CHECK` rather than a vocabulary table (`format.cadence`/`asset.status` and
 * siblings), not the cross-Brand, independently-evolving kind of set `hook_type`/`theme` are. Purely
 * additive: `ALTER TABLE ... ADD COLUMN`, touching no existing column, row, or constraint — migration 1's
 * and migration 2's own shipped SQL is untouched, mirroring how migration 3 (issue #209) added a whole
 * new table without touching either earlier migration.
 */
const MIGRATION_4: Migration = {
  version: 4,
  description: "Adds idea.hook_type_source / idea.theme_source — queryable classification provenance.",
  sql: `
ALTER TABLE idea ADD COLUMN hook_type_source TEXT CHECK (hook_type_source IS NULL OR hook_type_source IN ('heading', 'inferred'));
ALTER TABLE idea ADD COLUMN theme_source TEXT CHECK (theme_source IS NULL OR theme_source IN ('heading', 'inferred'));
`,
};

/** Every migration, in ascending version order. A future schema change (a new table, a widened
 *  vocabulary, a relaxed constraint) is a NEW entry appended here, never an edit to an already-shipped
 *  migration's SQL — migration 2 (issue #219), migration 3 (issue #209), and migration 4 (issue #206)
 *  are all cases of this rule actually being exercised. */
export const MIGRATIONS: readonly Migration[] = [MIGRATION_1, MIGRATION_2, MIGRATION_3, MIGRATION_4];

/** The schema version a freshly migrated database ends up at — the highest version in `MIGRATIONS`. */
export const CURRENT_SCHEMA_VERSION: number = Math.max(...MIGRATIONS.map((m) => m.version));
