/**
 * The Hook Type / Theme backfill classification data (issue #206) — the 51 real Briefs (of the 61 total)
 * that carry a `## Hook concept`/`## Hook Concept` heading, each hand-read and classified against the
 * two closed vocabularies. The remaining 10 Briefs (all MundoTip, issue #219) carry neither a hook
 * heading nor a `format` field — there is nothing to read, so they are deliberately ABSENT from this
 * list and stay the importer's own honest `unclassified` default (never guessed here to look complete).
 *
 * This is a genuine classification job, not a schema detail (issue #206's own framing) — every entry
 * below was read by a person (an engineering agent, working from the issue's own instruction to optimise
 * for reviewability over throughput), not generated by a keyword matcher, and every one records BOTH its
 * classification and a plain-English `rationale` naming the exact hook text (or Brief-wide reading) that
 * justifies it, so the Operator's own sample review (`handoff.md`) can be checked against this source,
 * not just trusted.
 *
 * **Provenance (`hookTypeSource`/`themeSource`) is real, not decorative.** `'heading'` means the Brief's
 * own Hook concept heading NAMES the technique/subject near-verbatim (e.g. idea-02's hook literally says
 * "the skeptic's question", idea-04's says "the counter-intuitive promise") — a direct parse.
 * `'inferred'` means the heading names no literal technique, so the classification rests on reading the
 * Brief's hook prose as a WHOLE (e.g. idea-05's "a spot in Claude that thinks like you" fits `oddity`'s
 * definition without ever using that word). Every `rationale` states which case applies and why.
 *
 * **Matched by content hash, never by file path, at backfill run time.** `briefSha256` is the SHA-256 of
 * the exact Brief content `src/importer/load-brief.ts` read at import time (`sha256(Buffer.from(content,
 * "utf8"))`) — the SAME string `idea.brief` now holds verbatim. `src/hook-theme-backfill/backfill.ts`'s
 * `planBackfill` matches each committed `idea` row to its classification by hashing `idea.brief` and
 * looking it up here — never by reconstructing a legacy folder path (which the importer itself had to
 * handle four different shapes of, `src/importer/plan-idea.ts`'s own doc comment). This also makes drift
 * SAFE rather than silent: if a Brief file is ever hand-edited after import, its hash changes, the match
 * fails, and `planBackfill` reports it as unmatched rather than applying a stale classification to
 * content nobody re-read (`classifications.test.ts`'s own `"every classified entry's briefSha256
 * matches the REAL Brief file on disk"` test proves the reverse: today, before any drift, every hash DOES
 * match).
 *
 * **The vocabulary-mismatch escape hatch (`kind: "reported"`) exists as real, tested code, even though
 * this real batch never needed it.** Every one of the 51 Briefs read for this ticket genuinely fit one of
 * the ten closed Hook Types — unsurprising, since `src/vocabulary/theme.ts`'s own doc comment records
 * the Theme set was calibrated against a sample of these same real Briefs at authoring time. Had one NOT
 * fit, the entry for it would be `{ kind: "reported", briefSha256, briefPath, title, reason }` instead of
 * `{ kind: "classified", ... }` — `planBackfill` (`backfill.ts`) treats that as a REPORT, never a forced
 * near-miss, and `backfill.test.ts` proves that mechanism with synthetic data, since none of the 51 real
 * entries exercises it.
 *
 * Pure data: no disk, no network, no clock. `classifications.test.ts` is the ONE place this hash is
 * checked against the real files on disk (a test path, exempt from the `node:fs` boundary guard).
 */

import type { HookType } from "../vocabulary/hook-type.ts";
import type { Theme } from "../vocabulary/theme.ts";
import type { ClassificationSource } from "../idea/store.ts";

export type { ClassificationSource };

/** One Brief, successfully classified against BOTH closed vocabularies, with the provenance of each and
 *  a plain-English rationale a human can check. */
export interface ClassifiedBrief {
  readonly kind: "classified";
  /** SHA-256 of the exact Brief content `load-brief.ts` read at import time — the match key against a
   *  committed `idea.brief` (never a reconstructed file path). */
  readonly briefSha256: string;
  /** The repo-relative path this classification was read from — documentation only (readability in this
   *  file and in `classifications.test.ts`'s failure messages); never used to locate the Idea at
   *  backfill run time. */
  readonly briefPath: string;
  /** The Brief's own title (its H1 heading, or its YAML frontmatter `title`) — for the handoff's sample
   *  table and this file's own readability, never written to the database. */
  readonly title: string;
  readonly hookType: HookType;
  readonly hookTypeSource: ClassificationSource;
  readonly theme: Theme;
  readonly themeSource: ClassificationSource;
  /** The plain-English "how it was arrived at" a human can check against the real hook text — the
   *  Operator's own added condition (`handoff.md`'s sample table draws directly from this field). */
  readonly rationale: string;
}

/** One Brief whose hook text genuinely fits NO closed Hook Type (or subject fits no Theme) — reported,
 *  never forced into the nearest term (issue #206's central acceptance criterion). `planBackfill`
 *  surfaces this distinctly from both `"classified"` updates and an unmatched Idea; it never writes
 *  anything for a Brief in this state. */
export interface ReportedBrief {
  readonly kind: "reported";
  readonly briefSha256: string;
  readonly briefPath: string;
  readonly title: string;
  /** Why this Brief was reported instead of classified — names which vocabulary (Hook Type, Theme, or
   *  both) it does not fit, and what about the hook text does not match any closed member. */
  readonly reason: string;
}

export type BriefClassificationEntry = ClassifiedBrief | ReportedBrief;

/**
 * The 51 real, readable Briefs, hand-classified (issue #206). Deliberately does NOT include the 10
 * headingless MundoTip Briefs — see this module's own doc comment.
 */
export const BRIEF_CLASSIFICATIONS: readonly BriefClassificationEntry[] = [
  // --- data/brands/straw-motion/ideas/2026-W29 ---
  {
    kind: "classified",
    briefSha256: "c7ff926e829d9a87c0d22ca555b806195bdf891a3d7a4f089085b4d67eb7c3e4",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-01.md",
    title: "AI just got a job: the three assistants that now do the work for you",
    hookType: "reframe",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "Hook literally says \"Open on the reframe that your AI stopped being a chat window\" -- reframe named directly. Subject: three AI assistants (ChatGPT Work, Claude Cowork, Meta Muse Spark) shipping hands-off task features -- a product/tool release story.",
  },
  {
    kind: "classified",
    briefSha256: "c213fafd645ee1d670bfcf652d3981aaa114fcb364a90ccf42249f8403a226da",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-02.md",
    title: "GPT-5.6 is live for everyone: the 60-second no-hype rundown",
    hookType: "skeptics_question",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "Hook says \"pivot straight to the skeptic's question -- worth the hype or not\" -- skeptics_question named directly. Subject: GPT-5.6's general release, a product story.",
  },
  {
    kind: "classified",
    briefSha256: "366e44e5fb50d20ff200c465d12eb68d0eff56100ca6b4eb6083a1e1296bd79a",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-03.md",
    title: "Grok 4.5 vs Claude Opus 4.8: cheaper AND better at code?",
    hookType: "underdog_upset",
    hookTypeSource: "heading",
    theme: "comparison_or_benchmark",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on the underdog-upset framing -- the cheaper challenger beating the premium name\" -- underdog_upset named directly. Subject: a head-to-head cost/code benchmark between two named models.",
  },
  {
    kind: "classified",
    briefSha256: "c0b11a6f4713ef4c16fd9aa25dd9576657868281e2079977d041826504ab5e0b",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-04.md",
    title: "Claude's flagship is back -- and Anthropic showed a cheaper way to run it",
    hookType: "counter_intuitive",
    hookTypeSource: "heading",
    theme: "pricing_or_cost",
    themeSource: "heading",
    rationale:
      "Hook says \"Open on the counter-intuitive promise -- near-flagship results for a fraction of the price\" -- counter_intuitive named directly, and price is the explicit throughline.",
  },
  {
    kind: "classified",
    briefSha256: "9b0b60e74c2f3e497568d897ae12b49f349a741f7157c1c604e02fce74d4491a",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-05.md",
    title: "Anthropic found the spot in Claude that thinks like you",
    hookType: "oddity",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "No literal technique named; \"a spot in Claude that thinks like you\" is one specific, strange research finding demanding explanation -- closest to oddity. Subject: an interpretability finding about the model itself.",
  },
  {
    kind: "classified",
    briefSha256: "4baa98c05b1658109c70aded0210e6785de09f335b2546cb058cd55716924bbf",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-06.md",
    title: "X just built a whole video studio into the app -- no camera needed",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"a studio, inside a social app\" recasts X as something categorically different -- no literal word used, but the shape matches reframe. Subject: X's new in-app video-studio feature.",
  },
  {
    kind: "classified",
    briefSha256: "da973f9adfc09a9800013aff128f2770ca51d5eeebcd1805ff0aafeaf442102c",
    briefPath: "data/brands/straw-motion/ideas/2026-W29/idea-07.md",
    title: "AI images just got absurdly cheap -- here's what that actually changes",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "pricing_or_cost",
    themeSource: "heading",
    rationale:
      "Hook says \"Open on the jaw-dropping number -- pennies for a thousand images\" -- a stark figure carries the open, near-verbatim to surprising_number's own wording. Subject: an AI-image cost collapse.",
  },
  // --- data/brands/straw-motion/ideas/unhypped-daily/2026-08-11 ---
  {
    kind: "classified",
    briefSha256: "d00d93012d806cdd96b170da69924b81406453972845ffab520f0d37426f23c4",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-01.md",
    title: "Meta open-weighted a 30B model that runs on one gaming GPU, then wrote 6,000 words about why",
    hookType: "collision",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "\"Open on the split screen inside one day\" places two things (a word count, a model's size) in the same moment for comparison -- collision's shape, not its literal word. Subject: Meta's 30B open-weight model release.",
  },
  {
    kind: "classified",
    briefSha256: "760afbb920cb1c777d42e5e9722d17bc182b2828dbd39bd65bcde48fab8dfbb2",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-02.md",
    title: "OpenAI paused a model for hacking too well, then shipped a hacking model three days later",
    hookType: "collision",
    hookTypeSource: "heading",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "Hook literally says \"Open on the collision of the two announcements inside one day.\" Subject: a hacking-capable model paused then sold -- a danger/safety story.",
  },
  {
    kind: "classified",
    briefSha256: "610931d55dfe39ccaa5769b9e0e277accad372168694f4d9e597beb2e6b8dab7",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-03.md",
    title: "Nvidia is becoming the bank of AI: Apollo, Blackstone and Goldman are lining up $500 billion",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "industry_or_business",
    themeSource: "heading",
    rationale:
      "\"the role swap, not the number\" recasts Nvidia as a lender, a categorically different role -- reframe's shape. Subject: a $500B financing arrangement, a company/industry move.",
  },
  {
    kind: "classified",
    briefSha256: "00805876888deb9ddcaa99b839bcc305e341e75f928315e35a60afef68a69ca0",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-04.md",
    title: "Four labs shipped AI that listens while it talks, and one of them answers in 450 milliseconds",
    hookType: "surprising_number",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "The headline centers one stark figure, \"450 milliseconds,\" carrying the open, though the hook text itself never uses the word \"number.\" Subject: four labs' full-duplex voice AI feature.",
  },
  {
    kind: "classified",
    briefSha256: "ba009af5803c3105bc819638e4e4f6297df40a413d0b67dcbf06a3c9614a1ce6",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-05.md",
    title: "One Amazon data center is permitted to emit 33 million tons of CO2 a year",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "safety_or_risk",
    themeSource: "inferred",
    rationale:
      "Hook says \"This one comes with a tonnage figure: 33 million tons a year\" -- \"figure\" is near-verbatim to surprising_number's own wording. Subject: a data center's environmental permit, a danger/risk story.",
  },
  {
    kind: "classified",
    briefSha256: "08b66fb2e487e4e0f965ab7af92badf6e2441f91e9ae24e6b4e7a7738596c4c9",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-06.md",
    title: "Bernie Sanders asked AI companies to pause. The same day, $500 billion and a new open model said no.",
    hookType: "contradiction",
    hookTypeSource: "inferred",
    theme: "policy_or_regulation",
    themeSource: "heading",
    rationale:
      "The hook puts Sanders' ask and industry's response \"side by side\" as conflicting facts -- contradiction's own definition wording, not its literal term. Subject: a senator's regulatory pause request.",
  },
  {
    kind: "classified",
    briefSha256: "3759fcdef8c34d243db992d19c133810b17a5f6bd7641d547e81752f2b8d6716",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-07.md",
    title: "Zuckerberg wrote 6,000 words on superintelligence and said the word about 60 times",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "culture_or_reaction",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on the word count, not the ideas... roughly 60 uses\" -- an explicit count carries the open. Subject: a critique of hype-heavy corporate messaging vs substance -- a reaction/culture story.",
  },
  {
    kind: "classified",
    briefSha256: "6cae2282aca72450f14d15158511d6c3fba6a26f14d9657c0ba461ba70d75912",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-08.md",
    title: "A 30B agentic model now fits on one 24GB card: what that actually changes for builders",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "\"the agent brain... is now a file on your own drive\" recasts a subscription service as an owned object -- reframe's shape. Subject: an open-weight agentic model release.",
  },
  {
    kind: "classified",
    briefSha256: "3ae73b3d707b7fed1491177585a62d76db0d5f12a8bc772256de72cf8a663909",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-09.md",
    title: "In one day Meta, Nvidia and ByteDance all shipped models you can just download",
    hookType: "reversal",
    hookTypeSource: "inferred",
    theme: "industry_or_business",
    themeSource: "heading",
    rationale:
      "\"the surprise is which direction open now points... not from the scrappy end up\" -- an assumed direction is undone -- reversal's shape. Subject: major labs' open-sourcing move, an industry shift.",
  },
  {
    kind: "classified",
    briefSha256: "7c9e9a6c82a0c4f551fba01e6c8cbea52249806e5caa82a417a65ff8ac56a699",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-10.md",
    title: "An AI agent hacked a gym's booking system to move its own owner up the waitlist",
    hookType: "oddity",
    hookTypeSource: "inferred",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "\"The surprise is the venue. Not a bank, not a power grid, a gym waitlist\" -- one specific strange detail out of pattern, near-verbatim to oddity's own definition. Subject: an AI agent's unsafe/unintended action.",
  },
  {
    kind: "classified",
    briefSha256: "5e5cb642e2b98be94fc074ffdcce071f812af8341b57d5181efa23b4673e0375",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-11.md",
    title: "From Aug 14 Claude Code stops asking permission, and Anthropic says that is the safer setting",
    hookType: "reversal",
    hookTypeSource: "heading",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "Hook literally says \"Open on the reversal, not the release.\" Subject: removing a safety approval prompt.",
  },
  {
    kind: "classified",
    briefSha256: "eb521caae284f0292499c335ba69394b5119870eba0623fe94186cb2e3762180",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-08-11/idea-12.md",
    title: "OpenAI staff cashed out $7 billion, and San Francisco's housing market felt it",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "pricing_or_cost",
    themeSource: "inferred",
    rationale:
      "\"Open on the translation\" recasts an abstract AI boom into a concrete story -- reframe's shape. Subject: stock cashouts and housing prices -- money is the throughline.",
  },
  // --- data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august ---
  {
    kind: "classified",
    briefSha256: "b8c817e87d8923677b32da62094fd402eb39e71019e768aa77f39aa26a0913a4",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-01.md",
    title: "Google shipped Gemini 3.7 Flash three weeks after 3.6 -- and cut the price in half",
    hookType: "surprising_number",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "The hook centers one specific figure, the 21-day gap between releases, though it never uses the word \"number.\" Subject: a rapid model release.",
  },
  {
    kind: "classified",
    briefSha256: "d70458560db8755f46f3a5909a0df4b54c4493dc0943aa39bc1c9db370f37ef1",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-02.md",
    title: "Gemini 3.7 Flash reads an entire document in one second",
    hookType: "skeptics_question",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"questioning whether faster answers fix bad prompts\" opens on doubt and promises an honest verdict -- skeptics_question's shape. Subject: a model's read-speed feature.",
  },
  {
    kind: "classified",
    briefSha256: "862edc4f4edf9b461f3d33887a123f606a4c7eb4e97fe8c324fac294dd0834fa",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-03.md",
    title: "A quiet post-training update with a 500k context jump",
    hookType: "contradiction",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "Hook says \"Contrast the quiet nature of a post-training update with the massive... jump\" -- \"Contrast\" is a direct synonym for placing two facts side by side. Subject: a model update's capability jump.",
  },
  {
    kind: "classified",
    briefSha256: "e47a863aa5fbe470234c8eeaa0753c182aab5c5c3d15d725f6daf599c859b9fc",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-04.md",
    title: "Claude now looks at your open browser tabs",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"the shift from copying and pasting... to letting Claude look directly at your open browser tabs\" recasts the interaction mode -- reframe's shape. Subject: a new Claude capability.",
  },
  {
    kind: "classified",
    briefSha256: "db6ed7f81ba7d7e0d5593b02d35e412977364a1f2f82b02c66d61765f2f770d0",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-05.md",
    title: "The dirty secret of enterprise AI: agent loops and five-figure token bills",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "pricing_or_cost",
    themeSource: "heading",
    rationale:
      "\"the dirty secret of enterprise AI\" -- automation assumed to save money instead runs against that expectation. Subject: explicit \"five-figure monthly token bills,\" a cost throughline.",
  },
  {
    kind: "classified",
    briefSha256: "e65c9002bcfbf36d9d0b6b8273e8a38729de174683b4c7466ad81baeee8f6d1d",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-06.md",
    title: "No cloud server or Nvidia GPU needed for AI to control your laptop",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"you don't need a cloud server or an Nvidia datacenter GPU\" runs against the assumption that AI control needs heavy hardware. Subject: a locally-running AI capability.",
  },
  {
    kind: "classified",
    briefSha256: "324e5ddfe0900dd1024ad5c031edf263a381b941698e9d4fa5f62ba696f6ddb9",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-07.md",
    title: "$1B wanted, $15B offered, $5B taken at a $190B valuation",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "industry_or_business",
    themeSource: "heading",
    rationale:
      "Hook says \"Highlight the absurd numbers\" explicitly. Subject: a funding round's dollar figures -- a company/industry deal.",
  },
  {
    kind: "classified",
    briefSha256: "7d1f85950cc7772e6c8fdcb65cf3758b01fd004882df09be184544f61c7fc29f",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-08.md",
    title: "Western labs charge $15-30, DeepSeek sells near-frontier tokens for under a dollar",
    hookType: "underdog_upset",
    hookTypeSource: "inferred",
    theme: "pricing_or_cost",
    themeSource: "heading",
    rationale:
      "A cheaper challenger (DeepSeek) beats the premium incumbents at their own game on price -- underdog_upset's shape. Subject: explicit dollar-per-token prices compared.",
  },
  {
    kind: "classified",
    briefSha256: "20f449c309bb0612456f44981214ed7b7fe6cd538536898a4589b86a9d37a1a9",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-09.md",
    title: "The irony of Microsoft funding OpenAI while building rivals that beat it",
    hookType: "irony",
    hookTypeSource: "heading",
    theme: "industry_or_business",
    themeSource: "heading",
    rationale:
      "Hook says \"Note the irony of Microsoft funding OpenAI while quietly building models that beat\" -- irony named directly. Subject: a funding/competitive company dynamic.",
  },
  {
    kind: "classified",
    briefSha256: "2d4d52c8010e220e5d682b357bf858d5038e35044614bb45e8067278b999022b",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-10.md",
    title: "Every hour on Twitch was silently converted into training data for Amazon's models",
    hookType: "reversal",
    hookTypeSource: "inferred",
    theme: "safety_or_risk",
    themeSource: "inferred",
    rationale:
      "An assumed-private activity is \"silently\" revealed to have been repurposed -- an assumption undone. Subject: a data-use/privacy risk.",
  },
  {
    kind: "classified",
    briefSha256: "cda1771d00c53e825e1448ccdab169a0a33dc7426ff87ceb85f8b18a01e824cd",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-11.md",
    title: "The gap between viral CGI robot demos and manufacturing reality",
    hookType: "skeptics_question",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"Address the gap\" between hype and reality promises an honest verdict, not the marketing -- skeptics_question's shape. Subject: robotics/manufacturing capability.",
  },
  {
    kind: "classified",
    briefSha256: "910b3bd923ee1db6f49b2b22970f5f7084e577844a707350c1dd3255a1058dee",
    briefPath: "data/brands/straw-motion/ideas/unhypped-daily/2026-W33/friday-14-august/idea-12.md",
    title: "What a 'world model' actually means, now free to download",
    hookType: "reframe",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"Explain what a world model actually means in plain terms\" recasts a jargon term into something understandable -- reframe's shape. Subject: a new AI model release.",
  },
  // --- data/brands/straw-motion/ideas/unhypped-news/2026-W30 ---
  {
    kind: "classified",
    briefSha256: "895b35f520149cc62e6b3765b16f55b9a58fc1c5757c28bbef465468ea3b7035",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-01.md",
    title: "The best coding model this week is free to download -- and it's from China",
    hookType: "underdog_upset",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "\"not who you'd guess\" -- a lesser-known Chinese lab beats Silicon Valley at its own game -- underdog_upset's shape. Subject: a new coding model release (Kimi K3).",
  },
  {
    kind: "classified",
    briefSha256: "b856b5f6a47fd8a50f759208d408de60e0db45abc2d1d01668d7b183a653426c",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-02.md",
    title: "One chart: Chinese open models went from 1% to 69% of AI finetunes in a year",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "industry_or_business",
    themeSource: "heading",
    rationale:
      "Hook says \"Open on the single number that reframes the race\" -- \"number\" named directly. Subject: a market-share shift among AI labs.",
  },
  {
    kind: "classified",
    briefSha256: "b764bf5aa9e788dd0e347f563c2cfce9179884161399e65914decd1aaaa5f450",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-03.md",
    title: "AI just cracked math problems that stumped humans for decades -- and you can check the answer",
    hookType: "reframe",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on the reframe that separates this from usual AI hype\" -- reframe named directly. Subject: an AI capability achievement (a solved math conjecture).",
  },
  {
    kind: "classified",
    briefSha256: "bcdd69ea3548d14e1536fbb6ec0175d8314a2bb5de1dcfef2fe8fce43e5e5564",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-04.md",
    title: "There's now a $230 keyboard whose only job is babysitting your AI coding agents",
    hookType: "oddity",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "Hook says \"Open on the oddity -- a $230 keyboard that doesn't help you type.\" Subject: a new hardware gadget (Codex Micro).",
  },
  {
    kind: "classified",
    briefSha256: "740ecafbe51dc092360263b7a47e1089a7e6c126d227ee6f03873b17ec5aabeb",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-05.md",
    title: "One airline turned a weeks-long project into hours with ChatGPT Work",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "industry_or_business",
    themeSource: "inferred",
    rationale:
      "A weeks-long project compressed to hours runs against expectation. Subject: an airline's (Virgin Atlantic) operational case study with ChatGPT Work.",
  },
  {
    kind: "classified",
    briefSha256: "b60efde76c4d208bbaf94a1590324bcda78a528d3a3d85bc027eb81cd270a3b8",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-06.md",
    title: "OpenAI's first gadget isn't a phone -- it's a screenless speaker meant to live in your house",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "\"the subversion of expectations -- everyone assumed OpenAI's first device would be a phone\" -- outcome against expectation. Subject: a new hardware product.",
  },
  {
    kind: "classified",
    briefSha256: "adacbf37bc5cf2333769006eaf3fc69d62733a499f882a0591b0a5cab322af96",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-07.md",
    title: "An AI escaped its own test sandbox and pushed code to a public repo before anyone noticed",
    hookType: "oddity",
    hookTypeSource: "inferred",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "\"the unsettling specific -- a model got out of its own test box\" -- one strange detail demanding explanation. Subject: a safety-test leak.",
  },
  {
    kind: "classified",
    briefSha256: "99b10a8335db5f7df8c528b722cf21e6ffcb0efa5ccab515a59c886183edfcba",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-08.md",
    title: "Your AI tools might be uploading more than you think -- two leaks from one week",
    hookType: "collision",
    hookTypeSource: "inferred",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "\"two leaks from one week\" places two separate incidents in the same window for comparison -- collision's shape. Subject: data leaks.",
  },
  {
    kind: "classified",
    briefSha256: "610a155d130fddc5324296862e1b14333db1b3407a70680fde09e83be80eca9a",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-09.md",
    title: "One selfie and a voice clip now makes an AI avatar that reads any script",
    hookType: "reframe",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "Hook says \"the low bar that reframes video creation\" -- reframe named directly. Subject: a new AI avatar feature (Gemini Omni).",
  },
  {
    kind: "classified",
    briefSha256: "0cb37f0b238bb40b47275c974e4bdd1a2b96e159343bb378099e3d6b08bd2ccc",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W30/idea-10.md",
    title: "Claude just went two ways at once: free for every US teacher, and logging into your accounts",
    hookType: "reframe",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "Hook says \"The reframe: Claude is leaving the chat window in two directions at once\" -- reframe named directly. Subject: two new Claude feature launches.",
  },
  // --- data/brands/straw-motion/ideas/unhypped-news/2026-W32 ---
  {
    kind: "classified",
    briefSha256: "97e7004940497150d2113942b3ab6b326c2c7f0573beb4d3f7f6ef571d1ed2f4",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-01.md",
    title: "AI got 80% cheaper this week without getting any smarter",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "pricing_or_cost",
    themeSource: "heading",
    rationale:
      "Getting cheaper without getting smarter runs against the assumption that price cuts follow capability jumps. Subject: an explicit 80%/$0.20 price cut.",
  },
  {
    kind: "classified",
    briefSha256: "aa8c9f89c2ca863731c06bea78071d27ce63c5fac36b39d3331e2125ebb5cb9a",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-02.md",
    title: "OpenAI investigated one sandbox escape and found more",
    hookType: "counter_intuitive",
    hookTypeSource: "inferred",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "\"Most incident counts shrink as the story ages. This one grew\" runs against expectation. Subject: sandbox-escape safety incidents.",
  },
  {
    kind: "classified",
    briefSha256: "9860a7425846ef1a582e72071e2d3cd364f320e130ddf43d3d1c95a208d2296b",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-03.md",
    title: "The model did what the safety test asked. The test environment was the problem.",
    hookType: "reframe",
    hookTypeSource: "heading",
    theme: "safety_or_risk",
    themeSource: "heading",
    rationale:
      "Hook says \"The reframe is check what it can reach, not just what it will say\" -- reframe named directly. Subject: a safety-test failure (malware reaching real machines).",
  },
  {
    kind: "classified",
    briefSha256: "86d5eae790290fab5a561bceb62e58f708a79093f7270f9faaae433cb39afdb3",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-04.md",
    title: "53.4 to 45.4: the free model is ahead on the test that measures doing the job",
    hookType: "surprising_number",
    hookTypeSource: "inferred",
    theme: "comparison_or_benchmark",
    themeSource: "heading",
    rationale:
      "The hook centers two specific scores (53.4 vs 45.4) as the frame. Subject: an explicit benchmark comparison between two named models.",
  },
  {
    kind: "classified",
    briefSha256: "2fc0e6237d1d4a3d0cf554d832eb199f2469249954d6b22242ece90a01f03ea6",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-05.md",
    title: "The model behind your AI video can also move a robot's hand in 101 milliseconds",
    hookType: "collision",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on the collision: the family of models... is also driving physical robot manipulation.\" Subject: a dual-use model capability.",
  },
  {
    kind: "classified",
    briefSha256: "8b8eb73e9cd40d5c72d9787c0d5605c2df14372ef2caa3aa229998a26e4099a2",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-06.md",
    title: "Hollywood sent legal letters over 15-second AI clips. The new version makes 3 minutes.",
    hookType: "contradiction",
    hookTypeSource: "inferred",
    theme: "policy_or_regulation",
    themeSource: "inferred",
    rationale:
      "A scale jump (15s to 3min clips) is set directly against ongoing legal action -- two facts placed side by side. Subject: Hollywood's legal letters, a regulatory/IP backdrop.",
  },
  {
    kind: "classified",
    briefSha256: "7f5c6425d35de782466c058e0674477da49f196a01b30cd125d7d545b12e5c3c",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-07.md",
    title: "You can actually play the game it built: Grok Build turns a chat prompt into a live app",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "product_or_tool",
    themeSource: "heading",
    rationale:
      "Hook says \"reveal the 1,024-parallel-agents number as the scale behind it\" -- \"number\" named directly. Subject: a new AI coding/game-building capability.",
  },
  {
    kind: "classified",
    briefSha256: "bba98a7bea813ce55f2064b52a47791e8a3bd3b22e52642d4c7b0471140443a1",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-08.md",
    title: "The US floated sanctions over Kimi K3, then its own experts said the story was wrong",
    hookType: "reversal",
    hookTypeSource: "heading",
    theme: "policy_or_regulation",
    themeSource: "heading",
    rationale:
      "Hook says \"how fast the scary version was walked back\" -- \"walked back\" is literally in the reversal definition's own wording. Subject: a sanctions/regulatory reversal.",
  },
  {
    kind: "classified",
    briefSha256: "aa52fef1f9f429b07a772f5dabd4c4f23f476e986115929e1c9ad898b0e55b0f",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-09.md",
    title: "Three in four support issues now close without a human at BBVA and SoftBank",
    hookType: "surprising_number",
    hookTypeSource: "heading",
    theme: "industry_or_business",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on 75%\" -- an explicit stark figure. Subject: a company operations shift (support automation) at two named companies.",
  },
  {
    kind: "classified",
    briefSha256: "64676d00f1a66ed55f61c6b10f4369403a963335066e07fbed546c0903faab9b",
    briefPath: "data/brands/straw-motion/ideas/unhypped-news/2026-W32/idea-10.md",
    title: "A chipmaker posted record profits and $590 billion vanished in 48 hours",
    hookType: "contradiction",
    hookTypeSource: "heading",
    theme: "pricing_or_cost",
    themeSource: "inferred",
    rationale:
      "Hook says \"Open on the contradiction with the two numbers side by side: record profits, and about $590 billion gone.\" Subject: a stock-value swing -- money is the throughline.",
  },
];
